name: dart_pub_global
version: 1.0.0+1
environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  cider: ^0.1.1
  devtools: ^2.9.4
  flutter_gen: ^4.1.6
  flutterfire_cli: ^0.2.1+1
  fvm: ^2.3.1
  grinder: ^0.9.1
  yaml: ^3.1.0
dev_dependencies:
  pedantic_mono: any
